'use client';
import { Link } from '../i18n/navigation';
import { useEffect, useRef, useState } from 'react';
import { frameForProgress, timeline } from '../config/timeline';
import { Logo } from './Logo';
import { useTranslations } from 'next-intl';
function src(frame: number, mobile: boolean) { return `/frames${mobile ? '-mobile' : ''}/frame_${String(frame).padStart(3, '0')}.webp`; }
export function FrameStage() { const t = useTranslations('stage'); const canvasRef = useRef<HTMLCanvasElement>(null); const stageRef = useRef<HTMLDivElement>(null); const images = useRef<Record<string, HTMLImageElement>>({}); const [progress, setProgress] = useState(0); const [loaded, setLoaded] = useState(1);
  useEffect(() => { const canvas = canvasRef.current; const stage = stageRef.current; if (!canvas || !stage) return; const context = canvas.getContext('2d'); if (!context) return; let mobile = window.innerWidth < 768; let current = 1; let raf = 0;
    const draw = (frame: number) => { const image = images.current[src(frame, mobile)] || images.current[src(current, mobile)]; if (!image?.complete) return; current = frame; const scale = Math.max(canvas.width / image.naturalWidth, canvas.height / image.naturalHeight); const w = image.naturalWidth * scale; const h = image.naturalHeight * scale; context.clearRect(0, 0, canvas.width, canvas.height); context.drawImage(image, (canvas.width - w) / 2, (canvas.height - h) / 2, w, h); };
    const resize = () => { const ratio = Math.min(window.devicePixelRatio || 1, 1.5); canvas.width = innerWidth * ratio; canvas.height = innerHeight * ratio; canvas.style.width = `${innerWidth}px`; canvas.style.height = `${innerHeight}px`; draw(current); }; resize();
    const load = (frame: number) => { const key = src(frame, mobile); if (images.current[key]) return; const image = new Image(); image.src = key; image.onload = () => { images.current[key] = image; setLoaded((value) => Math.min(192, value + 1)); draw(current); }; };
    for (let i = 1; i <= 192; i += 8) load(i); load(1);
    const onScroll = () => { const rect = stage.getBoundingClientRect(); const next = Math.max(0, Math.min(1, -rect.top / (stage.offsetHeight - innerHeight))); setProgress(next); const frame = frameForProgress(next); for (let i = Math.max(1, frame - 3); i <= Math.min(192, frame + 3); i++) load(i); cancelAnimationFrame(raf); raf = requestAnimationFrame(() => draw(frame)); }; window.addEventListener('scroll', onScroll, { passive: true }); window.addEventListener('resize', resize); onScroll(); return () => { cancelAnimationFrame(raf); window.removeEventListener('scroll', onScroll); window.removeEventListener('resize', resize); };
  }, []);
  const beat = timeline.find((item) => progress >= item.start && progress <= item.end) ?? timeline[0]; const beatLabels = [t('assembled'), t('lift'), t('hidden'), t('sedimentation'), t('core'), t('output'), t('zero')]; return <section className="stage" ref={stageRef}><div className="stage-sticky"><canvas ref={canvasRef} className="stage-canvas"/><div className="stage-scrim"/><div className="stage-copy"><p className="eyebrow">{beatLabels[timeline.indexOf(beat)]} <span>•</span> 0{timeline.indexOf(beat) + 1}</p><h1>{progress < .3 ? <>{t('wastewater')}<br /><i>{t('transformed')}</i></> : progress < .46 ? <>{t('nothing')}<br /><i>{t('hiddenTitle')}</i></> : progress < .92 ? <>{t('nature')}<br /><i>{t('perfected')}</i></> : <>{t('clean')}<br /><i>{t('zero')}</i></>}</h1><p className="hero-description">{t('description')}</p><Link className="button" href="/quote">{t('clean')} <span>↗</span></Link></div><div className="stage-meta"><span>{t('scroll')}</span><div className="progress-line"><span style={{ width: `${progress * 100}%` }}/></div><span>{String(Math.round(progress * 192) || 1).padStart(3, '0')} / 192</span></div><div className="load-state"><Logo variant="mark" /><span>{t('description')} {Math.round((loaded / 192) * 100)}%</span></div></div></section>; }