'use client';
import { useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import { products } from '../data/products';

export function LeadForm() {
  const t = useTranslations('quote'); const locale = useLocale(); const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle'); const [message, setMessage] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus('sending'); const form = new FormData(event.currentTarget); const payload = { locale, name: form.get('name'), email: form.get('email'), phone: form.get('phone'), projectType: form.get('projectType'), model: form.get('model'), message: form.get('message'), website: form.get('website') }; try { const response = await fetch('/api/quote', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setMessage(result.message); setStatus('success'); event.currentTarget.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Please try again.'); setStatus('error'); } }
  if (status === 'success') return <div className="form-card form-success"><p className="eyebrow">BioGen Biotank</p><h2>{message}</h2></div>;
  return <form className="form-card" onSubmit={submit}><label>{t('projectType')}<select name="projectType"><option>Home</option><option>Apartment</option><option>Office</option><option>School</option><option>Resort</option></select></label><label>{t('model')}<select name="model">{products.map((product) => <option key={product.slug} value={product.name}>{product.name} · {product.litres} L</option>)}<option value="Not sure">{t('notSure')}</option></select></label><label>{t('name')}<input name="name" required minLength={2} placeholder={t('namePlaceholder')} /></label><label>{t('email')}<input name="email" required type="email" placeholder={t('emailPlaceholder')} /></label><label>Phone<input name="phone" type="tel" placeholder="+91 9566504484" /></label><label>{t('site')}<textarea name="message" placeholder={t('sitePlaceholder')} /></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label>{status === 'error' && <p className="form-error" role="alert">{message}</p>}<button className="button" type="submit" disabled={status === 'sending'}>{status === 'sending' ? 'Sending...' : t('submit')} <span>↗</span></button></form>;
}