import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { ProcessExperience } from '../../components/ProcessExperience';
import { GalleryExperience } from '../../components/GalleryExperience';
import { getTranslations } from 'next-intl/server';
import { LeadForm } from '../../components/LeadForm';
import { ProductDetail, ProductListing, SpecsComparison } from '../../components/ProductExperience';
import { getProduct, products } from '../../data/products';
const pages: Record<string, { title: string; lead: string; blocks: [string, string, string][] }> = {
  technology: { title: 'The intelligence is in the cycle.', lead: 'Anaerobic and aerobic treatment, tuned into one quiet system.', blocks: [['01', 'No chemicals', 'Biology does the heavy lifting. No harsh additives, no chemical dosing.'], ['02', 'Built to breathe', 'A considered flow path keeps each chamber balanced and the output clear.'], ['03', 'Made to last', 'Durable panels, simple access, and a layout designed for decades of service.']] },
  process: { title: 'Waste becomes water.', lead: 'Five calm steps move every drop from inlet to clear output.', blocks: [['01', 'Inlet', 'Wastewater enters the primary chamber without disturbing the cycle.'], ['02', 'Sedimentation', 'Heavy solids settle naturally, separating the first load from the flow.'], ['03', 'Anaerobic digestion', 'Beneficial bacteria break down organic matter across the biological core.'], ['04', 'Aerobic filtration', 'Oxygen-rich water is polished through the final chamber.'], ['05', 'Clear output', 'Safe, clarified water leaves ready for a garden or soak pit.']] },
  products: { title: 'Sized for real life.', lead: 'A modular family for homes, offices, hospitality, and everything in between.', blocks: products.map((product) => [product.name, `Up to ${product.users} users`, product.tagline] as [string, string, string]) },
  specs: { title: 'The details matter.', lead: 'A clear view of the numbers, materials, and maintenance behind BioGen.', blocks: [['Capacity', '2,600–5,600 L', 'Five models cover the everyday range.'], ['Performance', 'Passive by design', 'Low-energy operation with no chemical dosing.'], ['Maintenance', 'Simple access', 'Routine checks are designed to be quick and infrequent.']] },
  applications: { title: 'At home in more places.', lead: 'From a quiet garden to a busy resort, the same clear cycle adapts.', blocks: [['Homes', 'Private and peaceful', 'Reliable treatment that disappears into the landscape.'], ['Offices', 'Ready for rhythm', 'A responsible system for teams and visitors.'], ['Schools & resorts', 'Built for community', 'Practical water stewardship at a larger scale.']] },
  install: { title: 'Start with solid ground.', lead: 'A straightforward installation path, with the important decisions made early.', blocks: [['01', 'Site survey', 'Confirm soil, access, levels, and the destination for treated water.'], ['02', 'Set and connect', 'Place the tanks on a stable base and connect the flow path.'], ['03', 'Commission', 'Test the cycle, close the lids, and hand over a system ready to work.']] },
  sustainability: { title: 'A lighter footprint.', lead: 'Treatment that respects the water, energy, and space it depends on.', blocks: [['Water', 'Reuse with confidence', 'Return clear water to gardens and soak pits where appropriate.'], ['Energy', 'Passive operation', 'Let gravity and biology carry the process.'], ['Materials', 'Long-life thinking', 'Choose durability once, then maintain it simply.']] },
  about: { title: 'Designed for the world outside.', lead: 'BioGen exists to make responsible infrastructure feel natural, useful, and quietly beautiful.', blocks: [['Our mission', 'Make better normal', 'Clean water should be a thoughtful default, not a luxury.'], ['Our values', 'Clarity over complexity', 'We design the system so its purpose is easy to understand.'], ['Our promise', 'Stay close to the work', 'We keep listening to the people who install, live with, and maintain BioGen.']] },
  gallery: { title: 'See the cycle.', lead: 'A closer look at the system, the details, and the water moving through it.', blocks: [['Film', 'The disassembly', 'Watch the real 8-second sequence from assembled system to open cutaway.'], ['Posters', 'The detail', 'A visual library of the places and components that make the system work.'], ['Visit', 'The full story', 'Follow the process from inlet to clear output.']] },
  faq: { title: 'Good questions deserve clear answers.', lead: 'The practical details, without the jargon.', blocks: [['How often is maintenance needed?', 'Routine checks are simple', 'Most systems benefit from a monthly visual check and an annual service.'], ['Does BioGen smell?', 'It should not', 'A balanced biological cycle is designed to operate without harsh odors.'], ['How long does installation take?', 'Usually a few days', 'Timing depends on ground conditions, access, and the selected model.']] },
  contact: { title: 'Let’s make a plan.', lead: 'Tell us a little about your site and we’ll help shape the next step.', blocks: [['Email', 'rajmurugan307@gmail.com', 'For product, project, and partnership questions.'], ['Contact', '+91 9566504484', 'Call or message us about your project.'], ['Hours', '24/7', 'We are available around the clock.']] },
  blog: { title: 'Notes on better water.', lead: 'Field notes, practical guidance, and the thinking behind the system.', blocks: [['01 / Field note', 'What clear output really means', 'A practical guide to understanding treated water and reuse.'], ['02 / Design', 'Why the system is modular', 'The case for smaller, calmer biological steps.'], ['03 / Guide', 'Planning a retrofit', 'The early questions that save time later.']] }
  ,privacy: { title: 'Privacy, plainly stated.', lead: 'We only use the information you share to respond to your project or question.', blocks: [['01', 'What we collect', 'Name, contact details, and project context you choose to send us.'], ['02', 'Why we use it', 'To answer your request, prepare a quote, or improve the experience.'], ['03', 'Your control', 'Ask us to update or remove your information at any time.']] },
  terms: { title: 'Terms of use.', lead: 'A short, readable outline of how this site is intended to be used.', blocks: [['01', 'Information', 'Product figures and placeholder performance values should be confirmed for your site.'], ['02', 'Downloads', 'Technical documents are provided for early planning and are not a substitute for professional advice.'], ['03', 'Contact', 'Questions about a project are always welcome through the contact page.']] },
  'not-found': { title: 'Nothing hidden here.', lead: 'The page you are looking for has moved on. The cycle continues.', blocks: [['01', 'Return home', 'Start again from the BioGen overview.'], ['02', 'Explore the process', 'See how each chamber works.'], ['03', 'Ask a question', 'We are happy to help with a real project.']] }
};
function getPage(slug: string) { if (pages[slug]) return pages[slug]; if (slug.startsWith('blog-') || slug.startsWith('gallery-')) return { title: 'A closer look.', lead: 'The useful details are here, ready when you are.', blocks: [['01', 'A considered system', 'Clear information for a cleaner decision.'], ['02', 'Made for context', 'Every project starts with its place and people.'], ['03', 'Keep exploring', 'There is always another useful question to ask.']] }; return null; }
export function generateStaticParams() { return products.flatMap((product) => [{ slug: ['products', product.slug] }, { slug: [product.slug] }]); }
export default async function InnerPage({ params }: { params: { slug: string[] } }) { const slug = params.slug.join('-'); const productSlug = params.slug[0] === 'products' ? params.slug[1] : undefined; const product = productSlug ? getProduct(productSlug) : undefined; const processT = await getTranslations('process'); const galleryT = await getTranslations('gallery'); const quoteT = await getTranslations('quote'); const pageT = await getTranslations('pages'); const contactT = await getTranslations('contact'); if (['biogen-home-1000', 'biogen-plus-3000', 'biogen-pro-6000'].includes(slug)) redirect('/products'); if (slug === 'products' && !productSlug) return <ProductListing />; if (productSlug && product) return <ProductDetail product={product} />; if (slug === 'process') return <main><section className="page process-heading"><p className="eyebrow">{processT('eyebrow')}</p><h1>{processT('title')}</h1><p>{processT('lead')}</p></section><ProcessExperience /></main>; if (slug === 'gallery') return <main className="page"><section className="page-header"><p className="eyebrow">{galleryT('eyebrow')}</p><h1>{galleryT('title')}</h1><p>{galleryT('lead')}</p></section><GalleryExperience /></main>; const data = getPage(slug); const isQuote = slug === 'quote'; if (!data && !isQuote) notFound(); const localizedPage = data && pageT.has(slug) ? { title: pageT(`${slug}.title`), lead: pageT(`${slug}.lead`) } : data ? { title: data.title, lead: data.lead } : undefined; const localizedBlocks = slug === 'contact' ? [['Email', 'rajmurugan307@gmail.com', contactT('emailText')], ['Contact', '+91 9566504484', contactT('phoneText')], ['Hours', '24/7', contactT('hoursText')]] as [string, string, string][] : data?.blocks; return <main className="page"><section className="page-header"><p className="eyebrow">BIOGEN BIOTANK <span>•</span> {slug.replaceAll('-', ' ')}</p><h1>{isQuote ? quoteT('title') : localizedPage!.title}</h1><p>{isQuote ? quoteT('lead') : localizedPage!.lead}</p></section>{isQuote ? <LeadForm /> : <><section className="content-grid">{localizedBlocks!.map(([no, title, text]) => <article className="info-block" key={no}><span>{no}</span><h2>{title}</h2><p>{text}</p></article>)}</section><section className="page-cta"><h2>{processT('output')}<br /><i>{processT('outputText')}</i></h2><Link className="button" href="/quote">{quoteT('submit')} <span>↗</span></Link></section></>}</main>; }